<a href="https://colab.research.google.com/github/cown0211/AITech_5th/blob/main/Pre-Course/3_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  수식을 행렬형태로 작성하려면?
  
  아래와 같이 리스트 형태로...

  ```
  coefficient_matrix = [[2,2,1], [2,-1,2], [1,-1,2]]
  constant_vector = [9,6,5]
  ```

  but

  matrix가 커질수록 리스트는 비효율적!

  
  # **NumPy**

In [ ]:
# array 생성

a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [ ]:
import numpy as np

a = np.array(a, int) # 사용할 리스트, 데이터 타입
a

array([1, 2, 3, 4, 5])

In [ ]:
test_array = np.array([1,"4",5.3,8], float) # 생성할 리스트, 데이터 타입
print(test_array)
print(type(test_array[3]))

# numpy의 np.array는 하나의 데이터 type만 넣을 수 있음

[1.  4.  5.3 8. ]
<class 'numpy.float64'>


## NumPy array vs Python List

* 파이썬 리스트는 데이터의 주소를 저장함

 * 값은 이미 정적인 공간에 들어가있고 그 값으로 접근하는 주소를 저장하는 개념

* 넘파이 어레이는 값 자체를 저장해버림

In [ ]:
a[0] is b[-1]

# a[0] == 1, b[-1] == 1이지만 각각 주소를 저장하기 때문에 True
# 파이썬이 저장하는 1의 주소가 같다는 의미

True

In [ ]:
a = np.array(a)
b = np.array(b)
a[1] is b[-2]

# ndarray에서는 값 자체를 저장하고, 각 어레이가 다른 메모리에 할당돼있으므로 False

False

## shape, dtype

* shape: numpy array의 dimension 구성을 반환

* dtype: numpy array의 데이터 type 반환

In [ ]:
test_array.dtype
# ndarray는 모두 같은 타입을 가짐

dtype('float64')

In [ ]:
a = [[1,2,3], [4,5,6], [4,5,6]]
np.array(a).shape

(3, 3)

## reshape

* array shape을 변경, element 갯수는 동일

In [ ]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape # 2*4 matrix

(2, 4)

In [ ]:
np.array(test_matrix).reshape(8,) # 2행4열 행렬을 8행1열 벡터로 변환

array([1, 2, 3, 4, 1, 2, 5, 8])

In [ ]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [ ]:
np.array(test_matrix).reshape(-1,2)
# -1; size를 기반으로 row 개수 선정
# 여기에선 전체 element = 8이고, reshape 열 개수를 2로 했으므로 
# row를 4로 자동으로 선정

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [ ]:
np.array(test_matrix).reshape(2,-1)
# 열을 알아서 4개로 선정

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [ ]:
np.array(test_matrix).reshape(2,2,2)
# 3차원으로 재정렬

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [ ]:
np.array(test_matrix).reshape(1,-1,2)
# 열을 알아서 4개로 선정

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

## flatten

* 다차원 array를 1차원 array로 변환

In [ ]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]] # 2,2,4 mat
np.array(test_matrix).flatten()
# 2,2,4 mat -> 16 열벡터

(16,)

## indexing

In [ ]:
a = np.array([[1,2,3], [4.5,5,6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(a[0][2])
print(a[0,2])

3
3


In [ ]:
a[0][0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [ ]:
a[0,0] = 12
a

array([[12,  2,  3],
       [ 4,  5,  6]])

## slicing

In [ ]:
a = np.array([[1,2,3,4,5], [4.5,5,6,62,5], [1,2,4,6,3], [5,3,6,7,8]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6, 62,  5],
       [ 1,  2,  4,  6,  3],
       [ 5,  3,  6,  7,  8]])

In [ ]:
a[:,1] # 2번째 열만 추출

array([2, 5, 2, 3])

In [ ]:
a[2:4,3:5]

array([[6, 3],
       [7, 8]])

In [ ]:
a[1] # 2번째 행만 추출

array([ 4,  5,  6, 62,  5])

In [ ]:
a[:, ::2] # 2칸씩 뛰어서 추출

array([[1, 3, 5],
       [4, 6, 5],
       [1, 4, 3],
       [5, 6, 8]])

In [ ]:
a[::2, ::3] # 2칸씩, 3칸씩 추출

array([[1, 4],
       [1, 6]])

## creation function

In [ ]:
 # arange; array 범위를 지정하여 값의 list 생성

np.arange(30) # list의 range와 같음

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0, 5, 0.6) # 시작, 끝, step

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8])

In [ ]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
# ones, zeros and empty

# zeros; 0만 있는 ndarray
np.zeros(shape=(10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros((2,5)) # 2 by 5 mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# ones; 1만 있는 ndarray

np.ones(shape = (10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# empty; shape만 주어지고 값은 비어있는 ndarray 생성
# 메모리만 잡고 값은 x, 이전에 할당된 값이 표현

np.empty(shape = (10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.empty((3,5))

array([[3.99432707e-316, 3.85371204e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05162657e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.81019663e-310]])

In [ ]:
# something_like; ndarray의 shape 크기 만큼 1,0 또는 empty array 반환

test_matrix = np.arange(30).reshape(5,6)
np.empty_like(test_matrix)

array([[   48858016,           0,           3,           0, 34359738373,
                  0],
       [          0, 17179869185,           0,           0,           0,
                  0],
       [          0,           0,           0,           0,           0,
                  0],
       [          0, 17179869185,           0,           0,           0,
                  0],
       [          0,           0,           0,    44302328,    79810944,
                  0]])

In [ ]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## identity

단위행렬 생성

In [ ]:
np.identity(n=3, dtype = np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

## eye

대각선의 값이 1이고, k로 index 변경이 가능

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.eye(3, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## diag

대각 행렬의 값을 추출, k로 index 조정

In [ ]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


In [ ]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix, k = 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]


## random sampling

데이터 분포에 따른 sampling으로 array 생성

In [ ]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.63642901, 0.70917155, 0.94367368, 0.02670333, 0.44726251],
       [0.35980325, 0.92190251, 0.38038028, 0.67924035, 0.34001774]])

In [ ]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.56585113,  0.32985024, -0.01195053,  0.74610163,  0.52741899],
       [ 0.134003  , -0.25648522, -0.5567959 , -1.6608065 ,  0.21276222]])

In [2]:
np.random.exponential(scale = 2, size = 100)

array([1.86657287e+00, 5.36916920e-01, 1.08927591e+00, 3.96459475e+00,
       7.91131250e-01, 6.57956870e-01, 5.07354720e+00, 1.24089300e+00,
       3.21657351e+00, 1.21917570e+00, 7.44380510e-01, 6.46621218e+00,
       1.77965718e+00, 2.06892407e+00, 9.91215464e-02, 2.89284599e-01,
       1.67519693e+00, 1.67722642e+00, 5.19980731e-01, 1.07652293e+01,
       8.92526193e-02, 1.83246366e+00, 1.02827683e+01, 2.49790493e+00,
       1.82002319e+00, 1.38685034e+00, 7.73432166e-02, 7.39346657e-01,
       9.42868999e+00, 4.14708871e+00, 1.56088974e+00, 7.83827240e-01,
       7.38821478e-01, 2.90286563e-01, 1.66279425e+00, 3.51522922e+00,
       5.65046456e-01, 2.43471866e+00, 1.93467376e+00, 9.22679750e-01,
       2.49761145e+00, 1.21153413e+00, 3.95830352e-02, 1.88889021e+00,
       3.92336292e-02, 1.46636859e+00, 1.46437720e-01, 8.06963051e+00,
       1.22653150e+00, 2.02127101e+00, 3.75959981e-02, 2.50009854e+00,
       1.04122376e+00, 3.02606719e+00, 2.63507445e+00, 8.94317461e-02,
      

# operation functions

## sum

* ndarray의 element 간의 합을 구함, list sum과 동일

In [3]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
test_array.sum()
# np의 sum()

55

In [5]:
sum(test_array)
# list sum과 결과 똑같

55

## axis

* 모든 operation func. 실행 시 기준이 되는 dimension 축

* 데이터 삽입 시 가장 최근 데이터의 rank가 뒤로 밀림

* 3 by 4 mat 생성 시 3; axis 0 // 4; axis 1

In [6]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
test_array.sum(axis = 0)
# axis = 0이므로 행끼리 합함

array([15, 18, 21, 24])

In [8]:
test_array.sum(axis = 1)

array([10, 26, 42])

In [11]:
third_order_tensor = np.array([test_array, test_array, test_array, test_array, test_array])
third_order_tensor
# 5 by 3 by 4 mat
# 3 by 4를 5개 합쳐놓은 꼴이므로
# axis = 0 -> 5
# axis = 1 -> 3
# axis = 2 -> 4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [12]:
third_order_tensor.sum(axis = 0)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [13]:
third_order_tensor.sum(axis = 1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [14]:
third_order_tensor.sum(axis = 2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

## mean & std

In [19]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [21]:
test_array.std(axis=1), test_array.std(axis=0)

(array([1.11803399, 1.11803399, 1.11803399]),
 array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

## concatenate & stack

* numpy array를 합치는(붙이는) 함수

In [24]:
a = np.array([1,2,3])
b = np.array([2,3,4])
# 1 by 3 vec


np.vstack((a,b))
# 2 by 3 mat

array([[1, 2, 3],
       [2, 3, 4]])

In [26]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
# 3 by 1 vec


np.hstack((a,b))
# 3 by 2 mat

array([[1, 2],
       [2, 3],
       [3, 4]])

In [31]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
# 1 by 3 vec

# concatenate()는 axis를 설정해줄 수 있음
# 이해하기 쉬우려면 붙인 결과 기준으로 0은 행, 1은 열로 붙이는 것

np.concatenate((a,b), axis=0)
# axis = 0이므로 1by3의 1이 기준이므로 행으로 쌓음

array([[1, 2, 3],
       [2, 3, 4]])

In [43]:
a = np.array([[1,2], [3,4]]) # 2x2
b = np.array([5,6])          # 1x2

print(a.shape)
print(b.shape) # 형태가 (2,)라서 연산이 불가, 

b = b[np.newaxis, :] # np.newaxis로 디멘션 추가
print(b.shape) # 형태가 (1,2)로 수정됨

# 아니면 아래 셀처럼 처음부터 [[5,6]]으로 생성하는 방법도 있음

(2, 2)
(2,)
(1, 2)


In [33]:
a = np.array([[1,2], [3,4]]) # 2x2
b = np.array([[5,6]])        # 1x2

np.concatenate((a,b.T), axis=1)
# 2x2와 1x2를 붙이려니 안붙음 -> b.T 연산으로 맞춰줌

array([[1, 2, 5],
       [3, 4, 6]])

## operations b/t arrays

* array 간의 사칙연산

In [51]:
test_a = np.array([[1,2,3], [4,5,6]], float)
test_a
# 2by3 mat

array([[1., 2., 3.],
       [4., 5., 6.]])

In [52]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [53]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
test_a * test_a
# 행렬곱이 아니고 같은 위치의 element 간의 연산
# (1,1)에 위치한 1과 1의 곱
# (2,3)에 위치한 6과 6의 곱

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

## dotproduct(), 행렬곱

In [55]:
test_a @ test_a.T
# 행렬곱은 @로 연산

array([[14., 32.],
       [32., 77.]])

In [57]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

# dot() 연산으로도 행렬곱 가능
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

## transpose

In [58]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

## broadcasting

* shape이 다른 배열 간의 연산을 지원

* vec-scalar 뿐만 아니고 vec-mat 연산도 지원

* shape이 달라도 그냥 구조를 확장시켜서 shape을 맞춰버리는 연산이므로 주의 필요!!

In [64]:
test_mat = np.array([[1,2,3], [4,5,6]], float)
print(test_mat)

scalar = 3

[[1. 2. 3.]
 [4. 5. 6.]]


In [65]:
test_mat + scalar
# 차원이 달라도 스칼라에 해당하는 값을 test_mat의 모든 칸에 연산함

array([[4., 5., 6.],
       [7., 8., 9.]])

In [67]:
test_mat = np.arange(1,13).reshape(4,3)
test_vec = np.arange(10,40,10)
# 4yb3 mat와 1by3 vec

print(test_mat, "\n", test_vec)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
 [10 20 30]


In [68]:
test_mat + test_vec
# 둘을 더해버리면 test_vec를 강제로 4by3 mat으로 확장시킨 뒤 연산해버림

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

# comparisions

## all & any

In [71]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a < 4
# array의 모든 element가 4 미만인지를 T/F로 반환

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [76]:
np.any(a > 8)
# 하나라도 True -> True
# 전부 False -> Flase

True

In [77]:
np.all(a > 5)
# 전부 True -> True
# 하나라도 False -> False

False

## comparison operation 1

* 배열의 크기고 동일하면 같은 위치의 element 간의 비교 결과를 bool type array로 반환

In [78]:
test_a = np.array([1,2,56], int)
test_b = np.array([5,3,1], int)

test_a > test_b

array([False, False,  True])

In [79]:
test_a == test_b

array([False, False, False])

In [80]:
(test_a > test_b).any()
# test_a가 test_b보다 하나라도 크면 True

True

## comparison operation 2

In [81]:
a = np.array([1,3,0], float)
np.logical_and(a>0, a<3)
# a>0의 결과 T T F
# a<3의 결과 T F T
# logical_and는 and 연산과 같으므로 T F F 반환

array([ True, False, False])

In [84]:
b = np.array([True, False, True], bool)
np.logical_not(b)
# b의 결과 T F T
# not 붙이면 F T F

array([False,  True, False])

In [86]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)
# b의 결과 T F T
# c의 결과 F T F
# b와 c의 or 연산 T T T

array([ True,  True,  True])

## np.where

In [88]:
np.where(a>0, 3, 2)
# where(condition, True, False)
# a>0의 연산 결과를 T,F로 반환하고
# T인 자리에는 3을
# F인 자리에는 2를 넣음

array([3, 3, 2])

In [95]:
a = np.arange(5,15)
np.where(a>10)
# condition만 넣어주면 T인 인덱스만 반환

(array([6, 7, 8, 9]),)

In [96]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)
# NaN(Not a Number) 값만 True로 반환

array([False,  True, False])

In [97]:
np.isfinite(a)
# is finite number

array([ True, False, False])

## argmax & argmin

* array 내 최대or최소값의 index 반환

In [106]:
a = np.array([1,23,5,5,216,24,1,623,6,3,4])
np.argmax(a), np.argmin(a)

(7, 0)

In [107]:
a[np.argmax(a)]
# np.argmax(a)가 인덱스를 반환하므로 a[~]는 그 값을 반환

623

In [101]:
# axis 기반의 반환

a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
print(np.argmax(a), np.argmin(a))
# axis 지정 안해주면 그냥 0,0부터 끝까지 한줄로 나열한 것으로 계산

print(np.argmax(a, axis=1), np.argmin(a, axis=0))
# axis를 기준으로 반환

5 0
[3 1 1] [0 0 2 2]


In [102]:
a.argsort()
# 행,렬을 기반으로 각 element의 오름차순 순번을 반환

array([[0, 1, 2, 3],
       [2, 0, 3, 1],
       [2, 3, 0, 1]])

# boolean & fancy index

## boolean index

* 특정 조건에 따른 값을 배열 형태로 추출

* comparison operation 함수들도 모두 사용 가능

In [108]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3
# 해당 조건과 각 element를 비교하여 T/F array 반환

array([False,  True, False, False, False,  True,  True,  True])

In [109]:
test_array[test_array > 3]
# 조건이 True인 index의 element를 추출

array([4., 8., 9., 7.])

In [110]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

## fancy index

In [111]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 인덱스로 활용해야 하기 때문에 int 선언!!

a[b]
# bracket idnex, b 배열의 값을 index로 하여 a 값 추출

array([2., 2., 4., 8., 6., 4.])

In [112]:
a.take(b)
# take() 메서드; bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [115]:
# mat 형태의 데이터도 가능

a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
# mat_a에서 b를 행index, c를 열index로 변환

a[b,c]
# a[0,0], a[0,1], a[1,1], a[1,1], a[0,1]

array([ 1.,  4., 16., 16.,  4.])

In [118]:
a[b]
# row index 적용하기도 가능

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

# numpy data i/o

## load & save txt

In [ ]:
a = np.loadtxt("./populations.txt", delimiter = "\t")
# populations.txt라는 파일을 가져오고, tab을 띄어쓰기로 구분

In [ ]:
np.savetxt("int_data_2.csv", a_int_3, fmt = "%.2e", delimiter = ",")

## numpy object - npy

In [ ]:
np.save("npy_test_object", arr = a_int_3)
# pickle 형태로 저장함

In [ ]:
a_test = np.load(file = "npy_test_object.npy")
a_test

In [ ]:
npy_array = np.load(file = "npy_test.npy")
npy_array