<a href="https://colab.research.google.com/github/cown0211/AITech_5th/blob/main/Pre-Course/3_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  수식을 행렬형태로 작성하려면?
  
  아래와 같이 리스트 형태로...

  ```
  coefficient_matrix = [[2,2,1], [2,-1,2], [1,-1,2]]
  constant_vector = [9,6,5]
  ```

  but

  matrix가 커질수록 리스트는 비효율적!

  
  # **NumPy**

In [12]:
# array 생성

a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [6]:
import numpy as np

a = np.array(a, int) # 사용할 리스트, 데이터 타입
a

array([1, 2, 3, 4, 5])

In [9]:
test_array = np.array([1,"4",5.3,8], float) # 생성할 리스트, 데이터 타입
print(test_array)
print(type(test_array[3]))

# numpy의 np.array는 하나의 데이터 type만 넣을 수 있음

[1.  4.  5.3 8. ]
<class 'numpy.float64'>


## NumPy array vs Python List

* 파이썬 리스트는 데이터의 주소를 저장함

 * 값은 이미 정적인 공간에 들어가있고 그 값으로 접근하는 주소를 저장하는 개념

* 넘파이 어레이는 값 자체를 저장해버림

In [13]:
a[0] is b[-1]

# a[0] == 1, b[-1] == 1이지만 각각 주소를 저장하기 때문에 True
# 파이썬이 저장하는 1의 주소가 같다는 의미

True

In [11]:
a = np.array(a)
b = np.array(b)
a[1] is b[-2]

# ndarray에서는 값 자체를 저장하고, 각 어레이가 다른 메모리에 할당돼있으므로 False

False

## shape, dtype

* shape: numpy array의 dimension 구성을 반환

* dtype: numpy array의 데이터 type 반환

In [15]:
test_array.dtype
# ndarray는 모두 같은 타입을 가짐

dtype('float64')

In [19]:
a = [[1,2,3], [4,5,6], [4,5,6]]
np.array(a).shape

(3, 3)

## reshape

* array shape을 변경, element 갯수는 동일

In [20]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape # 2*4 matrix

(2, 4)

In [21]:
np.array(test_matrix).reshape(8,) # 2행4열 행렬을 8행1열 벡터로 변환

array([1, 2, 3, 4, 1, 2, 5, 8])

In [23]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [24]:
np.array(test_matrix).reshape(-1,2)
# -1; size를 기반으로 row 개수 선정
# 여기에선 전체 element = 8이고, reshape 열 개수를 2로 했으므로 
# row를 4로 자동으로 선정

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [25]:
np.array(test_matrix).reshape(2,-1)
# 열을 알아서 4개로 선정

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [26]:
np.array(test_matrix).reshape(2,2,2)
# 3차원으로 재정렬

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [27]:
np.array(test_matrix).reshape(1,-1,2)
# 열을 알아서 4개로 선정

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

## flatten

* 다차원 array를 1차원 array로 변환

In [31]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]] # 2,2,4 mat
np.array(test_matrix).flatten()
# 2,2,4 mat -> 16 열벡터

(16,)

## indexing

In [32]:
a = np.array([[1,2,3], [4.5,5,6]], int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
print(a[0][2])
print(a[0,2])

3
3


In [34]:
a[0][0] = 10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [35]:
a[0,0] = 12
a

array([[12,  2,  3],
       [ 4,  5,  6]])

## slicing

In [37]:
a = np.array([[1,2,3,4,5], [4.5,5,6,62,5], [1,2,4,6,3], [5,3,6,7,8]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6, 62,  5],
       [ 1,  2,  4,  6,  3],
       [ 5,  3,  6,  7,  8]])

In [38]:
a[:,1] # 2번째 열만 추출

array([2, 5, 2, 3])

In [42]:
a[2:4,3:5]

array([[6, 3],
       [7, 8]])

In [43]:
a[1] # 2번째 행만 추출

array([ 4,  5,  6, 62,  5])

In [45]:
a[:, ::2] # 2칸씩 뛰어서 추출

array([[1, 3, 5],
       [4, 6, 5],
       [1, 4, 3],
       [5, 6, 8]])

In [46]:
a[::2, ::3] # 2칸씩, 3칸씩 추출

array([[1, 4],
       [1, 6]])

## creation function

In [48]:
 # arange; array 범위를 지정하여 값의 list 생성

np.arange(30) # list의 range와 같음

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
np.arange(0, 5, 0.6) # 시작, 끝, step

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8])

In [50]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
# ones, zeros and empty

# zeros; 0만 있는 ndarray
np.zeros(shape=(10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [52]:
np.zeros((2,5)) # 2 by 5 mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
# ones; 1만 있는 ndarray

np.ones(shape = (10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [55]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
# empty; shape만 주어지고 값은 비어있는 ndarray 생성
# 메모리만 잡고 값은 x, 이전에 할당된 값이 표현

np.empty(shape = (10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [57]:
np.empty((3,5))

array([[3.99432707e-316, 3.85371204e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05162657e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.81019663e-310]])

In [59]:
# something_like; ndarray의 shape 크기 만큼 1,0 또는 empty array 반환

test_matrix = np.arange(30).reshape(5,6)
np.empty_like(test_matrix)

array([[   48858016,           0,           3,           0, 34359738373,
                  0],
       [          0, 17179869185,           0,           0,           0,
                  0],
       [          0,           0,           0,           0,           0,
                  0],
       [          0, 17179869185,           0,           0,           0,
                  0],
       [          0,           0,           0,    44302328,    79810944,
                  0]])

In [60]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## identity

단위행렬 생성

In [61]:
np.identity(n=3, dtype = np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

## eye

대각선의 값이 1이고, k로 index 변경이 가능

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [65]:
np.eye(3, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [63]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## diag

대각 행렬의 값을 추출, k로 index 조정

In [67]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]


In [69]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix, k = 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]


## random sampling

데이터 분포에 따른 sampling으로 array 생성

In [70]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.63642901, 0.70917155, 0.94367368, 0.02670333, 0.44726251],
       [0.35980325, 0.92190251, 0.38038028, 0.67924035, 0.34001774]])

In [71]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.56585113,  0.32985024, -0.01195053,  0.74610163,  0.52741899],
       [ 0.134003  , -0.25648522, -0.5567959 , -1.6608065 ,  0.21276222]])